import { useState, type FormEvent } from "react";
import { ArrowLeft, ArrowRight, Check, Paperclip } from "lucide-react";

const input="w-full rounded-md border border-input bg-card px-3 py-3 text-sm outline-none focus:ring-2 focus:ring-ring";
const eventTypes=["Celebration","Seminar","Conference","Gala","Dinner","Launch","Exhibition / Booth","Opening","Other"];
const services=["Full Strategy","Stage & Curved LED Walls","AV & Sound","Intelligent Lighting","3D Booth Build","Branding & Crystal Giveaways","Media Coverage & Recap Video","VIP Registration & Ushers","Live Entertainment","Luxury Catering","Full Turnkey Execution"];
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-xs font-semibold text-mocha">{label}</span>{children}</label>}
function Done({onClose}:{onClose:()=>void}){return <div className="p-10 text-center"><div className="mx-auto grid size-14 place-items-center rounded-full bg-primary text-primary-foreground"><Check/></div><h3 className="mt-5 text-2xl font-semibold">Your request is ready.</h3><p className="mx-auto mt-3 max-w-md text-sm text-warmgray">Thank you. The AVERA team will contact you on the details provided to continue the consultation.</p><button onClick={onClose} className="mt-7 rounded-md bg-primary px-6 py-3 text-sm font-semibold text-primary-foreground">Close</button></div>}

export function CorporateWizard({onClose}:{onClose:()=>void}){
 const [step,setStep]=useState(1),[done,setDone]=useState(false),[selected,setSelected]=useState<string[]>([]);
 const toggle=(x:string)=>setSelected(v=>v.includes(x)?v.filter(i=>i!==x):[...v,x]);
 const next=(e:FormEvent)=>{e.preventDefault(); if(step<3)setStep(step+1); else setDone(true)};
 if(done)return <Done onClose={onClose}/>;
 return <form onSubmit={next} className="p-5 md:p-8"><div className="mb-8 grid grid-cols-3 gap-2">{["Scope","Services","Credentials"].map((x,i)=><div key={x}><div className={`h-1 ${i<step?"bg-primary":"bg-border"}`}/><p className="mt-2 text-[10px] font-semibold uppercase text-warmgray">0{i+1} {x}</p></div>)}</div>
 {step===1&&<div className="space-y-6"><div><p className="mb-3 text-xs font-semibold">Event Type</p><div className="flex flex-wrap gap-2">{eventTypes.map(x=><button type="button" key={x} onClick={()=>toggle(x)} className={`rounded-md border px-3 py-2 text-xs ${selected.includes(x)?"border-primary bg-primary text-primary-foreground":"border-border bg-card"}`}>{x}</button>)}</div></div><div className="grid gap-4 md:grid-cols-2"><Field label="Event date"><input required type="date" className={input}/></Field><Field label="Expected guests"><select required className={input} defaultValue=""><option value="" disabled>Select PAX</option>{["50","100","250","500","1000+"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Location"><select required className={input} defaultValue=""><option value="" disabled>Select location</option>{["Cairo — Downtown","Cairo — New Cairo","Cairo — Zayed / October","Red Sea — Hurghada","Red Sea — Gouna","Red Sea — Sokhna","North Coast / Sahel","Alexandria","Other"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Venue requirement"><select required className={input}><option>AVERA to source venue</option><option>Venue already confirmed</option><option>Still deciding</option></select></Field></div></div>}
 {step===2&&<div><p className="mb-4 text-sm text-warmgray">Select every service your project may require.</p><div className="grid gap-2 sm:grid-cols-2">{services.map(x=><button type="button" key={x} onClick={()=>toggle(x)} className={`flex items-center justify-between rounded-md border p-4 text-left text-sm ${selected.includes(x)?"border-primary bg-cream":"border-border bg-card"}`}>{x}{selected.includes(x)&&<Check className="size-4 text-ochre"/>}</button>)}</div></div>}
 {step===3&&<div className="grid gap-4 md:grid-cols-2"><Field label="Company name"><input required maxLength={100} className={input}/></Field><Field label="Contact person"><input required maxLength={100} className={input}/></Field><Field label="Title"><input required maxLength={100} className={input}/></Field><Field label="Work email"><input required type="email" maxLength={255} className={input}/></Field><Field label="Phone / WhatsApp"><input required type="tel" maxLength={30} className={input}/></Field><Field label="Target budget"><select required className={input}><option>Under EGP 250K</option><option>EGP 250K–500K</option><option>EGP 500K–1M</option><option>EGP 1M+</option></select></Field><Field label="Brief / RFP"><label className="flex cursor-pointer items-center gap-2 rounded-md border border-dashed border-border bg-card px-3 py-3 text-sm"><Paperclip className="size-4"/>Choose file<input type="file" className="sr-only" accept=".pdf,.doc,.docx,.ppt,.pptx"/></label></Field><div className="md:col-span-2"><Field label="Project notes"><textarea required maxLength={1500} rows={4} className={input}/></Field></div></div>}
 <div className="mt-8 flex justify-between"><button type="button" onClick={()=>step>1?setStep(step-1):onClose()} className="inline-flex items-center gap-2 rounded-md border border-border px-4 py-3 text-sm"><ArrowLeft className="size-4"/>{step>1?"Back":"Cancel"}</button><button type="submit" className="inline-flex items-center gap-2 rounded-md bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">{step===3?"Submit request":"Continue"}<ArrowRight className="size-4"/></button></div></form>
}

export function WeddingForm({onClose}:{onClose:()=>void}){const[done,setDone]=useState(false);if(done)return <Done onClose={onClose}/>;return <form onSubmit={e=>{e.preventDefault();setDone(true)}} className="p-5 md:p-8"><p dir="rtl" className="mb-7 rounded-md border border-border bg-cream p-4 text-right text-sm leading-relaxed">رجاءً ملء هذه الاستمارة بالبيانات الصحيحة لضمان قبول طلبك. جميع المعلومات سرية ولن يتم مشاركتها، وتُستخدم فقط لتنظيم حفل زفافك. 💍</p><div className="grid gap-4 md:grid-cols-2"><Field label="Groom & Bride names"><input required maxLength={150} className={input}/></Field><Field label="Wedding date"><input required type="date" className={input}/></Field><Field label="Number of guests"><input required type="number" min="1" max="5000" className={input}/></Field><Field label="Location"><select required className={input}><option>Downtown</option><option>New Cairo</option><option>Zayed & October</option><option>Ain Sokhna</option><option>Gouna</option><option>Sahel</option><option>Other</option></select></Field><Field label="Nationality"><select required className={input}><option>Egyptian</option><option>Foreigner</option></select></Field><Field label="Venue type"><select required className={input}><option>Indoor</option><option>Outdoor</option><option>Garden</option><option>Sea view</option></select></Field><Field label="Services needed"><select required className={input}><option>Venue</option><option>Decor</option><option>Makeup / Hair</option><option>Photo / Video</option><option>DJ</option><option>Singer</option><option>Full package</option><option>Other</option></select></Field><Field label="Budget / Prices starting from"><input required maxLength={100} className={input}/></Field><Field label="Contact Phone / WhatsApp"><input required type="tel" maxLength={30} className={input}/></Field><div className="md:col-span-2"><Field label="Additional notes"><textarea maxLength={1500} rows={4} className={input}/></Field></div></div><div className="mt-7 flex justify-end"><button className="rounded-md bg-primary px-6 py-3 text-sm font-semibold text-primary-foreground">Request wedding consultation</button></div></form>}